name: 'Code Review using Ollama'
description: 'Perform a code review on code modified using Ollama'

on:
  workflow_dispatch:

jobs:
  ollama:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ollama langchain langchain_community langchain-ollama beautifulsoup4

      - name: Install Ollama
        run: |
          curl -fsSL https://ollama.com/install.sh | bash

      - name: Run Ollama
        run: ollama serve gemma3:4b & python3 summarize.py

